### ISSUE TITLE
Remove blue focus borders from components that appear on click

### ISSUE THREAD

**Issue by ilinzweilin** [centrifuge/tinlake-ui#337] opened 2020-05-18 18:14 UTC
when does the border appear.
examples:
- loanlist when clicking on any row
- parent components when clicking on any link
- all buttons

**Comment by denniswell** [comment] 2020-05-19 20:39
Here are a few screenshots of these blue borders

![image](https://user-images.githubusercontent.com/48755923/82375762-57736500-9a21-11ea-8014-2f5f23c25a55.png)

![image](https://user-images.githubusercontent.com/48755923/82375870-87226d00-9a21-11ea-92c5-72204de90e5d.png)

![image](https://user-images.githubusercontent.com/48755923/82375917-9d302d80-9a21-11ea-980c-dee6093c0b77.png)

**Comment by philipstanislaus** [comment] 2020-06-04 12:59
I spent a few minutes looking into this. 

Removing the focus completely is easy, just pass `focusIndicator={false}` to all relevant grommet elements. Another way to achieve this quickly is by using the following: 

```css
button {
  outline: none !important;
  box-shadow: none !important;
}
```

I feel that we should not "fix" this using the above approaches though, because they remove the focus indicator completely, which severely impacts accessibility (and usability for people that like using their keyboards). 

The underlying issue here is that grommet uses JavaScript to re-implement focus state. The issue is reported and discussed in https://github.com/grommet/grommet/issues/3642 . There is one PR open that tries to solve the problem, but was abandoned: https://github.com/grommet/grommet/pull/3708

I feel the proper way to fix this issue is to contribute to grommet (possibly through a bounty).

Any thoughts?

**Comment by lucasvo** [comment] 2020-06-04 16:03
@philipstanislaus a bounty on grommet could be cool. can this be scoped well enough that we could ask someone to fix it though and do you think it will get merged?

**Comment by philipstanislaus** [comment] 2020-06-05 08:34
Yes, let me write a clearer spec for this. We can make the bounty dependent on a successful merge. There is some risk in no payout, but there’s the upside of having a paid grommet OSS contribution, which is a great reference.

**Comment by Tsourdox** [comment] 2020-06-17 10:07
I've tried multiple CSS variants for `outline: none`, but that only removes the built-in one in the browser. Is there a way to disable grommets focusIndicator globally? I have no need for this in the web application I'm creating and I don't want to add focusIndicator={false} everywhere.

**Comment by philipstanislaus** [comment] 2020-06-23 07:01
Hi @Tsourdox , not sure I understand the context – are you working on tinlake-ui?

**Closed** 2022-03-02 07:58 UTC
Labels: bounty candidate
